# Generated by Django 5.2.7 on 2025-10-23 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Wymowka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('glosy', models.IntegerField(default=0)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wymowki', to=settings.AUTH_USER_MODEL)),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wymowki', to='wymowki.kategoria')),
            ],
            options={
                'verbose_name_plural': 'Wymówki',
                'ordering': ['-data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to=settings.AUTH_USER_MODEL)),
                ('wymowka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='wymowki.wymowka')),
            ],
            options={
                'verbose_name_plural': 'Komentarze',
                'ordering': ['data_dodania'],
            },
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.IntegerField(choices=[(1, '👍'), (-1, '👎')])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wymowka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='wymowki.wymowka')),
            ],
            options={
                'verbose_name_plural': 'Oceny',
                'unique_together': {('wymowka', 'uzytkownik')},
            },
        ),
    ]
