# Generated by Django 5.2.7 on 2025-10-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wymowka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('glosy', models.IntegerField(default=0)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
